
const animalNames = [
  "Albatross",
  "Alligator",
  "Alpaca",
  "Anteater",
  "Antelope",
  "Armadillo",
  "Baboon",
  "Badger",
  "Bald eagle",
  "Bat",
  "Bear",
  "Beaver",
  "Bird",
  "Bison",
  "Black Bear",
  "Boa",
  "Boa constrictor",
  "Boar",
  "Buffalo",
  "Butterfly",
  "Camel",
  "Capybara",
  "Cat",
  "Cheetah",
  "Chimpanzee",
  "Chipmunk",
  "Cobra",
  "Cow",
  "Coyote",
  "Crab",
  "Crane",
  "Crocodile",
  "Crow",
  "Deer",
  "Dog",
  "Dolphin",
  "Dove",
  "Dragonfly",
  "Duck",
  "Eagle",
  "Echidna",
  "Elephant",
  "Elk",
  "Emu",
  "Falcon",
  "Ferret",
  "Fish",
  "Flamingo",
  "Flicker",
  "Fox",
  "Gazelle",
  "Gecko",
  "Giraffe",
  "Gnu",
  "Goat",
  "Goose",
  "Gorilla",
  "Grizzly bear",
  "Groundhog",
  "Gull",
  "Harbor seal",
  "Hawk",
  "Hedgehog",
  "Hen",
  "Hippopotamus",
  "Honey badger",
  "Hyena",
  "Iguana",
  "Insect",
  "Jackal",
  "Jaguar",
  "Kangaroo",
  "Killer whale",
  "Koala",
  "Komodo dragon",
  "Lemming",
  "Lemur",
  "Leopard",
  "Lion",
  "Lizard",
  "Llama",
  "Lynx",
  "Magpie",
  "Manatee",
  "Mockingbird",
  "Mongoose",
  "Monkey",
  "Moose",
  "Mouse",
  "Opossum",
  "Orca",
  "Ostrich",
  "Otter",
  "Owl",
  "Ox",
  "Peacock",
  "Pelican",
  "Penguin",
  "Pigeon",
  "Platypus",
  "Porcupine",
  "Possum",
  "Puma",
  "Python",
  "Rabbit",
  "Raccoon",
  "Rat",
  "Rattlesnake",
  "Rhinoceros",
  "Salmon",
  "Seal",
  "Sea lion",
  "Shark",
  "Sheep",
  "Skunk",
  "Sloth",
  "Snake",
  "Sparrow",
  "Spider",
  "Squirrel",
  "Starfish",
  "Swan",
  "Tapir",
  "Tarantula",
  "Tiger",
  "Tortoise",
  "Turkey",
  "Turtle",
  "Viper",
  "Vulture",
  "Wagtail",
  "Wallaby",
  "Whale",
  "Wolf",
  "Wombat",
  "Woodpecker",
  "Yak",
  "Zebra"
]

const adjectives = [
    "ancient","antique","aquatic","baby","basic","big","bitter","black","blue","bottle","bottled","brave","breezy","bright","brown","calm","charming","cheerful","chummy","classy","clear","clever","cloudy","cold","cool","crispy","curly","daily","deep","delightful","dizzy","down","dynamic","elated","elegant","excited","exotic","fancy","fast","fearless","festive","fluffy","fragile","fresh","friendly","funny","fuzzy","gentle","gifted","gigantic","graceful","grand","grateful","great","green","happy","heavy","helpful","hot","hungry","husky","icy","imaginary","invisible","jagged","jolly","joyful","joyous","kind","large","light","little","lively","lovely","lucky","lumpy","magical","manic","melodic","mighty","misty","modern","narrow","new","nifty","noisy","normal","odd","old","orange","ordinary","painless","pastel","peaceful","perfect","phobic","pink","polite","precious","pretty","purple","quaint","quick","quiet","rapid","red","rocky","rough","round","royal","rugged","rustic","safe","sandy","shiny","silent","silky","silly","slender","slow","small","smiling","smooth","snug","soft","sour","strange","strong","sunny","sweet","swift","thirsty","thoughtful","tiny","uneven","unusual","vanilla","vast","violet","warm","watery","weak","white","wide","wild","wilde","windy","wise","witty","wonderful","yellow","young","zany"
]

export function obfuscate(str: string) {
    let n = myhash(str);
    let max = adjectives.length * animalNames.length;

    let what = n % max;

    let adj = adjectives[Math.floor(what / animalNames.length)];
    let anm = animalNames[what % animalNames.length]?.toLowerCase();

    return `${adj}-${anm}`
}

function myhash(source: string) {
  let hash = 0, i, chr;
  if (source.length === 0) return hash;
  for (i = 0; i < source.length; i++) {
    chr = source.charCodeAt(i);
    hash = ((hash << 5) - hash) + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash);
}
