creation_rules:
  - pgp: >-
      73880ECAF69EC2ED44CE5889502BFB12D0B5295F
    age: >-
      age15d76eks3u78tsamnzywg0mtfhskte7gfyk930qgx8epvp04s5skst802ql,
      age1yubikey1qtcd3lj78mg3dqt9563x0ax25vsgjet2qtru44kcdxjhm9auqccjs9s7cul,
      age1yubikey1qfnshfsurzmvsx6jgvepq9qe8wnwlanuw92acl95mt6d2xykq7swk8mpkq2
